### ISSUE TITLE
Error 500 when saving changes on excluding all participants to myself as the organizer and excluding organizer to everyone

### ISSUE THREAD

**Issue by JoseGarzaIPS** [iodigital-com/SecretSanta#534]
I got this error while adding exclusions. I was trying to exclude myself of the party, adding all the participants as exclusions to me and adding me as exclusion to everyone, then this error appeared.

I'm used to organize them this exchange, but sometimes I don't participate. I got this working by adding a duplicate participant of myself with another email and excluding all so my first entry gives to my second, and vice versa.

**Comment by JoseGarzaIPS** [comment]
Also, when I got the email after the party started, I got %message as the party details inside the email. Maybe because I was using ES version and wrote word with acute accent or maybe is related to the previous 500 error.

**Comment by tvlooy** [comment]
Thanks for your report. This is not a use case we support but the 500 is not something we want

**Comment by gabazaba1986** [comment]
Hi Team, 

i'm experiencing the same issue issue - I cant even add now any exclusions - 
<img width="297" alt="secret santa error" src="https://github.com/user-attachments/assets/f5ccebff-29ef-459f-900c-4b8cf85bd9da">

I keep trying but its really defeating me each time now. 


Please help!!! 


Thanks 
Gabby

**Comment by JCarlosGarza** [comment]
Hi! I continue using the app. Seems like a timeout issue or something. When it happens to me I usually go exclusiones saving by groups so start with some of them and click save then continue with the rest. Hope it helps!

**Comment by gabazaba1986** [comment]
Hi @JCarlosGarza 

I've 78 users from around 7 coutries - what do you mean by saying: saving by goups? 
I maange to do 45% and when I request now even single name - I get error each time. 

So i consider now; cry, or do it all manaully - which lets be honest its lots of my time... 


or new app. 


Thanks in advance for any advice. 


Thanks 
Gabby

**Comment by tvlooy** [comment]
Don't do excessive excludes, it's not really made for this.

**Comment by gabazaba1986** [comment]
no probs I end up all manully, indeed what I plan for exclusions was way too big for this app. 

Thnk you very much for your replies @tvlooy & @JCarlosGarza!
