### ISSUE TITLE
500 Internal Server Error when trying to recall previous parties held

### ISSUE THREAD

**Issue by thegirlwithabow** [iodigital-com/SecretSanta#553]
I entered my email address to recall the previous party information.
Clicked the link in my email and got the above error message.
![Capture](https://user-images.githubusercontent.com/116788915/198208546-890ac9ec-d38f-4035-8e28-57ffd4bda1c4.PNG)

**Comment by tvlooy** [comment]
@thegirlwithabow thanks for your report. Fixed by @TomCan
