### ISSUE TITLE
Create a way to track present purchase/shipping by a participant 

### ISSUE THREAD

**Issue by ienadlard** [iodigital-com/SecretSanta#559]
Would help to also set a deadline for this, would make it easier to know who to bug to send their present. This doesn't mean tracking information just a statement saying "I have shipped/purchased the package on this date"

**Comment by RubenHollevoet** [comment]
I think the participants using this feature would be very limited.
You can always send a private message to your participant with tracking link or any other info you like.
Let's keep the interface clean and simple for now :)
