### ISSUE TITLE
Allow line breaks in wishlist

### ISSUE THREAD

**Issue by NadjaWipf** [iodigital-com/SecretSanta#571]
Hi, I love your Secret Santa organiser - thanks for making it free!

Here is a feature/change for the wishlist that I think would be great:
Instead of adding individual items to the wishlist, I'd like to be able to enter a (longer) free text that ALLOWS LINE BREAKS, so I can give my Secret Santa hints instead of specific items.
A sample wishlist text might look like this:

"Hello Secret Santa,

Here are some hints for my present.

I enjoy:
+ hiking & cycling
+ xy

Things I really don't need any more of are:
- clothes
- yz
... and by the way, I don't like the colour xx.

I look forward to your surprise.
Thank you. "

**Comment by RubenHollevoet** [comment]
Hi, thx for your request!

Ze would like to keep the interface as simple as possible to make the Santa experience very easy to understand. Takinig this into account we won't take any further staps and close the issue for now.

Nothing stays in your way trying to be creative and fit a personal Santa message on a single (or more) line ;)

**Comment by tvlooy** [comment]
If you attempt to implement it that would be nice!
