### ISSUE TITLE
Email redirects to phishing site when opened on a mobile device

### ISSUE THREAD

**Issue by zackslash** [iodigital-com/SecretSanta#572]
We have used this app in previous years but this year when emails are recieved and the "Find out your person" link on a mobile device is pressed it is redirecting participants to a Phishing site. This has been reported from multiple participants.

Note: This only seems to happen when the link is opened on a mobile device, it does not happen on desktop.

Note2: Canceling your party will stop participants who have not yet clicked the link from being redirected to the phishing site (instead they will recieve an error).

<img width="418" alt="Screenshot" src="https://github.com/iodigital-com/SecretSanta/assets/2040617/7aacbe5c-0764-43e0-bf31-ba0475401f59">

**Comment by RubenHollevoet** [comment]
hi @zackslash, thx for your report!
I am investigating the issue but but wasn't able to reproduce it yet.
My assumption would be that some 3th party tools (like corrupted browser plugins or other applications) on the device of the party creator have managed to infiltrate into the party details.
As I understood the party has been removed for now so I am unable to have a closer look for this specific case.
I assume you only had those experience for this specific party?

Anyhow, we will do some more research on this topic and take extra measurements to prevent such things from happening in the future.

**Comment by zackslash** [comment]
Hey @RubenHollevoet,
Thanks for the quick response.

We have been able to replicate this on multiple iOS devices (multiple individuals across multiple geographical locations).

It seems to be replicable with when creating any new party but only seems to redirect participants using iOS devices.

**Comment by zackslash** [comment]
It looks like the redirect may be happending in 'invoke.js', additionally blocking 'highcpmcreativeformat.com' at DNS level stops the redirects from happening, so I think these could be serving malicous ads in your pages.

```
document.write('<scr' + 'ipt type="text/javascript" src="//www.highcpmcreativeformat.com/4e46a9746a54e456c0123bd2f828c7c5/invoke.js"></scr' + 'ipt>');
```

**Comment by hvanoch** [comment]
I can say I am currently experiencing the same. As well my participants.

**Comment by RubenHollevoet** [comment]
Thanks for the extra investigation!
I will get in touch with the ones who are able to redeploy. Hopefully it will be fixed soon

@tvlooy could you checkout b3ae08b?

**Comment by tvlooy** [comment]
disabled adsterra stuff and discussing with marketing people

**Comment by JerrySievert** [comment]
I'm getting reports from my parents of mobile asking for credit card information and claims of this being a paid service.  neither have ad blockers on.

**Comment by tvlooy** [comment]
That's not good at all! Can you email your management page to? tom.vanlooy _at_ iodigital _dot_ com?
