### ISSUE TITLE
Romanian language

### ISSUE THREAD

**Issue by moldovanlaurean** [iodigital-com/SecretSanta#574]
Hi,
Is it possible for the interface of this website to be translated into Romanian?
I mention that I could help you with the translation of expressions. I have been using this site together with my team for several years, and we would appreciate it if the page were also translated into Romanian.

Thank you!

**Comment by tvlooy** [comment]
Sure we can add support for Romanian, if you can provide the translation. In https://github.com/iodigital-com/SecretSanta/tree/master/translations there is a messages.en.yaml and a validators.en.yaml file. You have to translate everything in that file to Romanian and open a merge request here on Github with the messages.ro.yaml and validators.ro.yaml files.
