### ISSUE TITLE
Ensuring Anonymous Drawing: Need to Exclude Myself as Organizer or not shoeing my name in the email invitation

### ISSUE THREAD

**Issue by Carollc10** [iodigital-com/SecretSanta#576]
The dynamic we're implementing involves everyone choosing a nickname, and you have to guess the person you were assigned by their wishlist. However, I can't do this on this platform because if I use a third-party email, there's no way to exclude the organizer. On the other hand, if I remain the organizer, the name I choose is revealed when sending the invitation, making it non-anonymous.

**Comment by tvlooy** [comment]
This is not supported. Sorry.
