### ISSUE TITLE
Are partial localization PR accepted?

### ISSUE THREAD

**Issue by jlocans** [iodigital-com/SecretSanta#577]
Hello!

Basically what the title asks. E.g. if FAQ page wasn't localized.

**Comment by tvlooy** [comment]
Yes! Updates and additions to existing translations are more than welcome. If you want to do an entire new language though, I want to start with a complete translation.

**Comment by jlocans** [comment]
Ok. I do indeed wish to add a new language - Latvian. And a follow up question - looking at the existing translations I assume that "Secret Santa" must remain as is everywhere and must not be localized?

**Comment by tvlooy** [comment]
You can choose to translate it or not. But in Dutch, my mother tongue, it would sound a bit silly, so I don't mind if you decide not to translate it.

**Comment by jlocans** [comment]
Okay, thanks! It will sound a bit silly either way, but if localized I think less so, because there are many people here who don't know what Secret Santa means.

**Comment by tvlooy** [comment]
And if you don't translate the FAQ that's fine.
