### ISSUE TITLE
Offer removal of ads for set fee to cover entire party

### ISSUE THREAD

**Issue by parkerhoward** [iodigital-com/SecretSanta#579]
Hi all,

Just wondering if there is any possibility of creating a "paid version" of the program with no ads.

For me personally, I'd be happy to pay ~$5-10 for the party to not see any ads.

I think this is truly the best website for Secret Santa, and love the way it functions. My only gripe is the amount of ads - which I understand, running something like this comes at a cost!

Hence, I'm wondering if a paid version would be possible / worthwhile. I'd even be interested in paying more for "lifetime" ad-free for myself and my parties.

Thank you!

**Comment by tvlooy** [comment]
I understand ads are annoying. This project is a collaboration between a developer team and a marketing team. Aside from the financial benefit, the marketing aspect is an important playground for us. (also note that we use our profits to sponsor charities and/or other open-source projects) A paid version is not something we had in mind in the near future.
