### ISSUE TITLE
exclude more than one email by participant error 500

### ISSUE THREAD

**Issue by stloc** [iodigital-com/SecretSanta#585]
![image](https://github.com/user-attachments/assets/f07823d1-2272-4538-a47d-7170e1783a64)

**Comment by stloc** [comment]
it's blocking...

**Comment by stloc** [comment]
it's happening today...

**Comment by tvlooy** [comment]
@stloc if you look at the code you will find that the algo to calculate matches based on excludes is not that fine tuned https://github.com/iodigital-com/SecretSanta/blob/master/src/Service/ParticipantShuffler.php#L29 if there are impossible combinations or if there are too many excludes it won't figure out a valid list and will fail. It should not throw a 500 though but feel free to provide a solution
