### ISSUE TITLE
Pairing does not seem random

### ISSUE THREAD

**Issue by Santiago-R** [iodigital-com/SecretSanta#586]
After using the site for a couple years with the same family group of 10+ people (perhaps minor deviations in pairing exclusions), too many of us got the exact same pairing as last year. Either this was a massive coincidence, or the pairing logic lacks randomness.

**Comment by TomCan** [comment]
As you can see [here](https://github.com/iodigital-com/SecretSanta/blob/a91b3993d0ea9281a9feca4b6cb599c79b2db304/src/Service/ParticipantShuffler.php#L68), pairing uses the [PHP shuffle function](https://www.php.net/manual/en/function.shuffle.php). Other than not being cryptographically secure, it should be random enough non the less.
