### ISSUE TITLE
Can't communicate email issue due contact form thinking I'm a robot.

### ISSUE THREAD

**Issue by Rudolphia63** [iodigital-com/SecretSanta#587]
I created two parties and one worked fine. The second validation email did not arrive. I tried asking for an overview email and it did not arrive either. No emails are in Spam. When I tried to use the contact form it rejected me saying it believed I am a robot. Do I provide my email address here to get help with this matter? Thanks!

**Comment by tvlooy** [comment]
Maybe you are a robot. How do I trust you?

**Comment by Rudolphia63** [comment]
I’m a little bit confused. How would anyone know if anyone is a robot? I
was just trying to get help because I was having trouble with the secret
Santa organizer. The problem seems to be resolved now.

I’m not super technical. I just needed help. I kind of feel like this
response was mean-spirited.

Srae

**Comment by tvlooy** [comment]
I would have to look into the issue with the recaptcha but it's not a black and white thing. My apologies for the remark that was not received as being funny.

**Comment by Rudolphia63** [comment]
Thank you for the apology. No big deal, I can see the humor in your joke. 🌻

Srae

**Comment by tvlooy** [comment]
I think it's fixed now. Thanks for your report @Rudolphia63
