### ISSUE TITLE
Inclusive Language

### ISSUE THREAD

**Issue by AS34565** [iodigital-com/SecretSanta#589]
Please could you alter the language sent in the 'Wishlist updated' email from 'his/her' to 'their' to be inclusive of non-binary folk! Thank you! 

![image](https://github.com/user-attachments/assets/553ca63d-31f5-471f-a3da-a43b7ed1095e)

**Comment by tvlooy** [comment]
small change, I dig it. Thanks for the suggestions. Fixed

**Comment by AS34565** [comment]
Oh amazing, thank you so much!
