### ISSUE TITLE
personal url does not keep language settings

### ISSUE THREAD

**Issue by MarcinPrzybysz** [iodigital-com/SecretSanta#591]
On admin page when I copy personal url it does not keep source language setting. Usually participants speak same language as admin.

**Comment by tvlooy** [comment]
I like that suggestion. This is fixed!

**Comment by MarcinPrzybysz** [comment]
Thank you! That was fast :)

pon., 25 lis 2024, 09:33 użytkownik Tom Van Looy ***@***.***>
napisał:
