### ISSUE TITLE
Submit an italian translation

### ISSUE THREAD

**Issue by ebaia-v** [iodigital-com/SecretSanta#596]
I tried to translate from English into Italian, where can i  submit correctely this file? 

here the link
[messages.it.yml](https://we.tl/t-TZjmaLCaQD)

**Comment by tvlooy** [comment]
@ebaia-v Thanks! I added the Italian translation. You should learn how to open changes from Github if you make improvements to the file now because the YML is very sensitive to indentation, quotes etc. I had to tweak your file to make it work.
