### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by toonamowasstolen** [iodigital-com/SecretSanta#599]
attempting to install code but get a error part way through, php 8.3

`/home/SecretSanta # composer instal
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
132 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In RecaptchaExtension.php line 15:
!!                                                                                 
!!    Warning: file_get_contents(/home/SecretSanta/config/recaptcha_secrets.json)  
!!    : Failed to open stream: No such file or directory                           
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
Script @auto-scripts was called via post-install-cmd`

**Comment by tvlooy** [comment]
```
Warning: file_get_contents(/home/SecretSanta/config/recaptcha_secrets.json)
!! : Failed to open stream: No such file or directory
```

In the repo the file is named recaptcha_secrets.json.dist (under the config directory). You can rename it to recaptcha_secrets.json to fix the error.
